module.exports = {
  M: 'M',
  L: 'L',
  XL: 'XL',
  ALL: 'Всі',
  Pizza: 'Піца',
  Hot: 'Гострі',
  Sushi: 'Суші',
  Chains: 'Сети',
  Drinks: 'Напої',
  Cheese: 'Сирні',
  Salads: 'Салати',
  Half: 'Половинки',
  Desserts: 'Десерти',
  Promotion: 'Акційні',
  Supplements: 'Додатки',
  MisoSoups: 'Місо супи',
  HotRoles: 'Гарячі роли',
  Philadelphia: 'Філадельфія',
  Vegetarian: 'Вегетаріанські',
  SushiAndRoles: 'Суші та роли',
  SoupsAndSalads: 'Супи та салати',
  DessertsAndDrinks: 'Десерти та напої'
};
