module.exports = {
  ALL: 'All',
  Hot: 'Hot',
  Half: 'Half',
  Pizza: 'Pizza',
  Sushi: 'Sushi',
  Chains: 'Chains',
  Drinks: 'Drinks',
  Cheese: 'Cheese',
  Salads: 'Salads',
  Desserts: 'Desserts',
  HotRoles: 'Hot roles',
  Promotion: 'Promotion',
  MisoSoups: 'Miso soups',
  Vegetarian: 'Vegetarian',
  Supplements: 'Supplements',
  Philadelphia: 'Philadelphia',
  SushiAndRoles: 'Sushi and roles',
  SoupsAndSalads: 'Soups and salads',
  DessertsAndDrinks: 'Desserts and drinks'
};
